# Add environment variable ANDROID_SDK_ROOT for cocos2d-x
export ANDROID_SDK_ROOT=/Users/redBit/Documents/android-sdk-macosx
export PATH=$ANDROID_SDK_ROOT:$PATH
export PATH=$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools:$PATH

# Add environment variable COCOS_CONSOLE_ROOT for cocos2d-x
export COCOS_CONSOLE_ROOT=/Users/redBit/Documents/dev/cocos2d-x-3.13.1/tools/cocos2d-console/bin
export PATH=$COCOS_CONSOLE_ROOT:$PATH

# Add environment variable COCOS_TEMPLATES_ROOT for cocos2d-x
export COCOS_TEMPLATES_ROOT=/Users/redBit/Documents/dev/cocos2d-x-3.13.1/templates
export PATH=$COCOS_TEMPLATES_ROOT:$PATH

# Add environment variable ANT_ROOT for cocos2d-x
export ANT_ROOT=/usr/local/Cellar/ant/1.9.6/bin
export PATH=$ANT_ROOT:$PATH

# Add environment variable NDK_ROOT for cocos2d-x
export NDK_ROOT=/Users/redBit/Documents/android-ndk-r10e/
export PATH=$NDK_ROOT:$PATH

# Add environment variable COCOS_X_ROOT for cocos2d-x
export COCOS_X_ROOT=/Users/redBit/Documents/dev
export PATH=$COCOS_X_ROOT:$PATH

# Add color
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\W\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'
alias la='ls -GFh -a'
alias lls='ls -l'
alias lla='la -l'
alias pd='pushd'
alias pp='popd'

# Add environment variable SDKBOX_HOME for sdkbox installer
export SDKBOX_HOME=/Users/redBit/.sdkbox
export PATH=${SDKBOX_HOME}/bin:$PATH

# Custom cmd
export ROVERS_PATH=~/Documents/dev/Rovers
export COOKIE_PATH=~/Documents/dev/CookieClickers_cocos

alias sb='source ~/.bash_profile'
alias eb='vim ~/.bash_profile'

alias vim='/usr/local/Cellar/vim/*/bin/vim'


function compilerelease
{
    if [ -d $1 ]; then
        cocos compile -s $1 -p android --android-studio --ap android-24 --app-abi armeabi-v7a -j8 -m release
    fi
}

function compiledebug
{
    if [ -d $1 ]; then
        cocos compile -s $1 -p android --android-studio --ap android-24 --app-abi armeabi-v7a -j8 -m debug
    fi
}

function installrelease
{
    if [ -d $1 ]; then
        adb install -r $1/bin/release/android/*.apk
    fi
}

function installdebug
{
    if [ -d $1 ]; then
        adb install -r $1/bin/debug/android/*.apk
    fi
}

function runrelease
{
    if [ -d $1 ]; then
        compilerelease $1; installrelease $1 
    fi
}

function rundebug
{
    if [ -d $1 ]; then
        compiledebug $1; installdebug $1
    fi
}
